### ISSUE TITLE
does not appear to have a file named pytorch_model.bin

### ISSUE THREAD

**Issue by remore2022** [pinokiofactory/RMBG-2-Studio#10]
Traceback (most recent call last):
  File "E:\pinokio\api\RMBG-2-Studio.git\app\app.py", line 35, in <module>
    birefnet = AutoModelForImageSegmentation.from_pretrained(
  File "E:\pinokio\api\RMBG-2-Studio.git\app\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 559, in from_pretrained
    return model_class.from_pretrained(
  File "E:\pinokio\api\RMBG-2-Studio.git\app\env\lib\site-packages\transformers\modeling_utils.py", line 3929, in from_pretrained
    raise EnvironmentError(
OSError: briaai/RMBG-2.0 does not appear to have a file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt or flax_model.msgpack.

(env) (base) E:\pinokio\api\RMBG-2-Studio.git\app>

**Comment by ai-anchorite** [comment]
you can see them here: https://huggingface.co/briaai/RMBG-2.0/tree/main

a connection issue between you and huggingface i assume.   maybe temporary congestion or something blocking - vpn, proxy, geolocation etc

**Comment by remore2022** [comment]
Thanks for your reply! 
I have upgraded to the latest version of pinokio and set up a global proxy, 
but it still doesn't work. 
An error occurred when downloading the pytorch_model.bin. 
I have downloaded this file separately, but I don't know which directory I should put it in.

**Comment by ai-anchorite** [comment]
hmm it's a HF snapshot download, i.e. the 864MB model file looks like this in the file system:

 `..pinokio\api\RMBG-2-Studio3.git\cache\HF_HOME\hub\models--briaai--RMBG-2.0\blobs\566ed80c3d95f87ada6864d4cbe2290a1c5eb1c7bb0b123e984f60f76b02c3a7"` 
 
 i actually have no idea how to easily insert a self downloaded model into that. 
 Claude or ChatGPT should be able to easily assist if you drag the `app.py` file into the chat and explain the problem. 
 
 the other thing to check will be why your system is blocking pinokio from downloading the file.  Could be as simple as a firewall or similar security being upset that a 3rd party app is downloading from Huggingface.
